version: '3.4'

services:
  auth-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "auth-db"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  auth-api:
    image: auth-api
    build:
      context: auth
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
    ports:
      - "8080:8080"

  products-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "products-db"
      
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data

  products-api:
    image: products-api
    build:
      context: products
      dockerfile: ./Dockerfile
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
  
  sales-db:
    image: tutum/mongodb
    restart: always
    environment:
      MONGODB_USER: "admin"
      MONGODB_PASS: "12345"
      MONGODB_DATABASE: "sales-db"
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data

  sales-api:
    image: sales-api
    build:
      context: sales
      dockerfile: ./Dockerfile
    environment:
      PORT: 8082
    ports:
      - "8082:8082"
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "25676:25676"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq/data
