server:
  port: ${PORT:8081}

spring:
  application:
    name: products-api

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:products-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:12345}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    maxActive: 3