INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY) VALUES (1000, 'Crise nas Infinitas Terras', 1000, 1000, 10);
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY) VALUES (1001, 'Harry Potter e a Pedra Filosofal', 1001, 1001, 10);